#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#lerna run --concurrency 1 --stream pre-commit --since HEAD --exclude-dependents
lerna run --concurrency 1 --stream precommit --since HEAD --exclude-dependents
